# Generated by Django 3.2.5 on 2021-10-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_task_belongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
