# Generated by Django 3.2.5 on 2021-10-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_project_project_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_intro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
