# Generated by Django 3.2.5 on 2021-10-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_project_project_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[(1, 'pending'), (2, 'active'), (3, 'waiting'), (3, 'finished')], default=1, max_length=200, null=True),
        ),
    ]
