# Generated by Django 3.2.5 on 2021-10-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Active'), ('3', 'Waiting'), ('4', 'Finished')], max_length=200, null=True),
        ),
    ]
