# Generated by Django 3.2.5 on 2021-10-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_project_project_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'Active'), ('3', 'Waiting'), ('4', 'Invoiced')], max_length=200, null=True),
        ),
    ]
